### ISSUE TITLE
KeyError: 'RANK' in os.environ["RANK"]

### ISSUE THREAD

**Issue by monajalal** [The-AI-Summer/pytorch-ddp#2]
```
$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ["RANK"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/envs/azureml_py38/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
>>> 

I have a machine with 8 GPUs and 24 CPUs. Why does RANK key doesn't exist? I am following your tutorial here:
https://theaisummer.com/distributed-training-pytorch/

and I wanted to do distributed training.
![Screenshot from 2022-12-13 10-04-40](https://user-images.githubusercontent.com/1892917/207369120-fa7ff30e-1c92-4013-8f96-17c81e2b01d4.png)




```

**Comment by black0017** [comment]
Hi!

Have you launched the script with `torchrun` or `torch.distributed.launch`? 

for pytorch < 1.9
```
python -m torch.distributed.launch --nproc_per_node=4 main_script.py
```

or  for pytorch > 1.9
```
torchrun --nproc_per_node=4 main_script.py
```
